[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Public Safety: Investigating the Applications and Impacts of Intelligent Technologies in Emergency Management"
